import mongoose from "mongoose";

const programSchema = mongoose.Schema({
	monAm1Title : String,
	monAm1Time : String,
	monAm2Title : String,
	monAm2Time : String,
	monAm3Title : String,
	monAm3Time : String,
	monPm1Title : String,
	monPm1Time : String,
	monPm2Title : String,
	monPm2Time : String,
	monPm3Title : String,
	monPm3Time : String,
	tueAm1Title : String,
	tueAm1Time : String,
	tueAm2Title : String,
	tueAm2Time : String,
	tueAm3Title : String,
	tueAm3Time : String,
	tuePm1Title : String,
	tuePm1Time : String,
	tuePm2Title : String,
	tuePm2Time : String,
	tuePm3Title : String,
	tuePm3Time : String,
	wedAm1Title : String,
	wedAm1Time : String,
	wedAm2Title : String,
	wedAm2Time : String,
	wedAm3Title : String,
	wedAm3Time : String,
	wedPm1Title : String,
	wedPm1Time : String,
	wedPm2Title : String,
	wedPm2Time : String,
	wedPm3Title : String,
	wedPm3Time : String,
	thursAm1Title : String,
	thursAm1Time : String,
	thursAm2Title : String,
	thursAm2Time : String,
	thursAm3Title : String,
	thursAm3Time : String,
	thursPm1Title : String,
	thursPm1Time : String,
	thursPm2Title : String,
	thursPm2Time : String,
	thursPm3Title : String,
	thursPm3Time : String,
	friAm1Title : String,
	friAm1Time : String,
	friAm2Title : String,
	friAm2Time : String,
	friAm3Title : String,
	friAm3Time : String,
	friPm1Title : String,
	friPm1Time : String,
	friPm2Title : String,
	friPm2Time : String,
	friPm3Title : String,
	friPm3Time : String,
});

const Program = mongoose.model("Program", programSchema);
export default Program;
